import Link from "next/link";
import { AlertTriangle, FileText, Scale, Cpu, CheckCircle } from "lucide-react";

export const metadata = {
  title: "Terms of Service | BasaltVigil Legal-Ops Platform",
  description: "Enterprise terms of service and computation-as-tool liability disclaimers.",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-[#020202] text-gray-300 font-sans pt-32 pb-24">
      <div className="max-w-4xl mx-auto px-6">
        {/* Header */}
        <div className="mb-16">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-white/5 border border-white/10 rounded-full text-xs font-mono tracking-widest text-gray-400 mb-6">
            <Scale size={14} className="text-[#b71928]" />
            LEGAL DOCUMENTATION
          </div>
          <h1 className="text-4xl md:text-5xl font-bold font-vox text-white mb-6 tracking-wide">Terms of Service</h1>
          <p className="text-xl text-gray-400 max-w-2xl">
            Governing your use of the Vigil Platform. By accessing our autonomous legal-ops swarm, you agree to these fundamental provisions.
          </p>
          <div className="mt-6 text-sm text-gray-500 font-mono">
            LAST UPDATED: May 3, 2026 | EFFECTIVE: May 3, 2026
          </div>
        </div>

        {/* Content */}
        <div className="space-y-12 text-sm leading-relaxed text-gray-300">
          
          <section className="glass-panel p-8 rounded-2xl border border-red-900/30 bg-gradient-to-b from-red-900/10 to-transparent relative overflow-hidden">
            <div className="absolute top-0 right-0 p-8 opacity-10 pointer-events-none">
              <AlertTriangle size={120} />
            </div>
            <h2 className="text-xl font-bold text-white mb-4 tracking-wider flex items-center gap-3">
              1. The Computation-as-Tool Disclaimer
            </h2>
            <p className="mb-4">
              BasaltVigil provides a suite of advanced Artificial Intelligence (AI) and Machine Learning (ML) tools designed to assist legal professionals, corporate officers, and authorized personnel. <strong>We do not provide formal legal advice, representation, or fiduciary services.</strong>
            </p>
            <ul className="space-y-3 mt-6">
              <li className="flex items-start gap-3">
                <div className="w-1.5 h-1.5 bg-[#b71928] rounded-full mt-2 shrink-0" />
                <p><strong>Augmentation, Not Replacement:</strong> Vigil operates under a <em>Computation-as-Tool</em> paradigm. The platform serves as a highly advanced computational assistant. All outputs, including drafted contracts, redlines, and legal analyses, must be reviewed, verified, and explicitly approved by a qualified, human attorney barred in the relevant jurisdiction.</p>
              </li>
              <li className="flex items-start gap-3">
                <div className="w-1.5 h-1.5 bg-[#b71928] rounded-full mt-2 shrink-0" />
                <p><strong>Limitation of Liability:</strong> Under no circumstances shall BasaltVigil, its parent company BasaltHQ, or its affiliates be held liable for any direct, indirect, incidental, or consequential damages resulting from errors, omissions, or inaccuracies generated by the AI swarm. The user assumes full professional responsibility for the final application of the generated artifacts.</p>
              </li>
              <li className="flex items-start gap-3">
                <div className="w-1.5 h-1.5 bg-[#b71928] rounded-full mt-2 shrink-0" />
                <p><strong>No Attorney-Client Privilege:</strong> Use of the platform does not establish an attorney-client relationship. While we enforce strict Zero-Retention confidentiality protocols, our platform is a software-as-a-service (SaaS) tool, not a law firm.</p>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4 tracking-wider">2. Account Registration & Security</h2>
            <p className="mb-4">
              To access the Platform, you must register using supported authentication methods (e.g., Thirdweb DID, Google, or Enterprise SSO). You are exclusively responsible for safeguarding your authentication credentials and cryptographic keys. Vigil cannot recover data lost due to compromised client-side credentials.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4 tracking-wider">3. Subscription & Billing</h2>
            <p className="mb-4">
              Vigil operates on a tiered subscription model governed by dynamic token usage parameters. By selecting a paid tier (Pro, Firm, or Enterprise), you authorize us to charge your provided payment method via our processor (Stripe) on a recurring basis.
            </p>
            <div className="grid md:grid-cols-2 gap-6 mt-6">
              <div className="bg-white/5 border border-white/10 rounded-xl p-6">
                <Cpu className="text-blue-400 mb-4" size={24} />
                <h3 className="font-bold text-white mb-2">Token Limitations</h3>
                <p className="text-xs text-gray-400">Each tier enforces a strict Monthly Token Limit representing your allocated computational bandwidth. Exceeding this limit will pause autonomous operations unless auto-topup is configured.</p>
              </div>
              <div className="bg-white/5 border border-white/10 rounded-xl p-6">
                <CheckCircle className="text-amber-400 mb-4" size={24} />
                <h3 className="font-bold text-white mb-2">Fair Use Policy</h3>
                <p className="text-xs text-gray-400">Unlimited ingestion clauses are subject to reasonable human limitations. Automated API abuse or coordinated denial-of-computation attacks will result in immediate suspension.</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4 tracking-wider">4. Custom Firm Playbooks</h2>
            <p className="mb-4">
              Users on eligible tiers may upload proprietary guidelines ("Custom Firm Playbooks"). You retain all intellectual property rights to your uploaded playbooks. Vigil guarantees that these instructions are isolated via our Zero-Retention protocol and will not bleed into the global context window of other tenants.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4 tracking-wider">5. Service Availability</h2>
            <p className="mb-4">
              We aim for 99.9% uptime, but the platform is provided on an "AS IS" and "AS AVAILABLE" basis. We reserve the right to perform scheduled maintenance, update foundational model dependencies, or patch vulnerabilities, which may temporarily disrupt service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4 tracking-wider">6. Dispute Resolution</h2>
            <p className="mb-4">
              Any dispute arising from or relating to these Terms shall be resolved through binding arbitration administered by the American Arbitration Association (AAA) in accordance with its Commercial Arbitration Rules, rather than in a court of law.
            </p>
          </section>
        </div>

        {/* Footer Actions */}
        <div className="mt-16 pt-8 border-t border-white/10 flex flex-col md:flex-row items-center justify-between gap-4">
          <Link href="/privacy" className="text-sm font-mono tracking-wider text-gray-500 hover:text-white transition-colors">
            &larr; READ PRIVACY POLICY
          </Link>
          <Link href="/" className="px-6 py-2 bg-white/10 hover:bg-white/20 text-white rounded font-mono text-xs tracking-widest transition-colors">
            RETURN TO PLATFORM
          </Link>
        </div>
      </div>
    </div>
  );
}
